# -*- coding: utf-8 -*-
"""LMP103S_Cantera_Analysis_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DyqbuPKFb93wsrmyNKFj-zsD9IXRh6x
"""

# ══════════════════════════════════════════════════════════════
# CELL 0 — Master Setup (Run this FIRST every session)
# Green Propellant Thermochemical Analysis
# Prashant Gahlot | University of Bologna | 2026
# ══════════════════════════════════════════════════════════════

# Install
!pip install cantera -q

# Imports
import cantera as ct
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import pandas as pd
import json
import os
from scipy import stats
from itertools import product

# Plot style
plt.rcParams.update({
    'figure.dpi'      : 150,
    'font.family'     : 'serif',
    'font.size'       : 11,
    'axes.titlesize'  : 12,
    'axes.labelsize'  : 11,
    'axes.grid'       : True,
    'grid.alpha'      : 0.3,
    'lines.linewidth' : 2.0,
    'lines.markersize': 7,
})

print(f"Cantera {ct.__version__} ready.")
print("All imports loaded.")

# ── Core data (hardcoded so no re-running needed) ──────────────

# LMP-103S decomposition products (Larsson et al. 2011)
LMP103S_decomp = {'N2': 0.3789, 'H2O': 0.4554, 'O2': 0.1657}
MW_LMP = 0.1657*32 + 0.3789*28 + 0.4554*18  # 24.11 g/mol

# Fuel definitions
FUELS = {
    'Ethanol': {'formula': {'C2H4':1.0,'H2':1.0}, 'MW':46.07,
                'color':'#2563A8', 'marker':'o'},
    'RP-1'   : {'formula': {'C2H4':6.0},           'MW':168.32,
                'color':'#D97706', 'marker':'s'},
    'Methane': {'formula': {'CH4':1.0},             'MW':16.04,
                'color':'#059669', 'marker':'^'},
}

OXIDIZERS = {
    'LMP103S': {'species': LMP103S_decomp,     'MW': MW_LMP,
                'color':'#DC2626', 'ls':'-'},
    'Pure_O2': {'species': {'O2':1.0},         'MW': 32.0,
                'color':'#7C3AED', 'ls':'--'},
}

OF_RATIOS = [2, 4, 6, 8, 10]
P_BAR     = 25  # chamber pressure
G0        = 9.80665

# ── Master simulation function ─────────────────────────────────
def run_equilibrium(fuel_name, ox_name, OF_mass, P_bar=P_BAR):
    gas    = ct.Solution('gri30.yaml')
    fdata  = FUELS[fuel_name]
    odata  = OXIDIZERS[ox_name]
    P_pa   = P_bar * 1e5

    mole_ratio = OF_mass * (fdata['MW'] / odata['MW'])
    mixture    = {}
    for sp, xf in odata['species'].items():
        mixture[sp] = mixture.get(sp, 0) + xf * mole_ratio
    for sp, m in fdata['formula'].items():
        mixture[sp] = mixture.get(sp, 0) + m

    gas.TPX = 300.0, P_pa, mixture
    gas.equilibrate('HP')

    T     = gas.T
    gam   = gas.cp / gas.cv
    MW    = gas.mean_molecular_weight
    R     = 8314.0 / MW
    Gvdk  = np.sqrt(gam) * (2/(gam+1))**((gam+1)/(2*(gam-1)))
    cstar = np.sqrt(R * T) / Gvdk
    Cf    = Gvdk * np.sqrt(2*gam/(gam-1)*(1-(1e5/P_pa)**((gam-1)/gam)))
    Isp   = Cf * cstar / G0

    top3 = {gas.species_names[i]: round(float(gas.X[i]),4)
            for i in np.argsort(gas.X)[-3:][::-1]}

    return {'T_c':round(T,1), 'Isp':round(Isp,2),
            'c_star':round(cstar,1), 'gamma':round(gam,4),
            'MW_ex':round(MW,3), 'exhaust':top3}

# ── Generate ALL results and cache them ───────────────────────
print("\nGenerating all simulation data...")
RESULTS = {}

for fname in FUELS:
    RESULTS[fname] = {}
    for oname in OXIDIZERS:
        RESULTS[fname][oname] = {}
        for OF in OF_RATIOS:
            try:
                r = run_equilibrium(fname, oname, OF)
                RESULTS[fname][oname][OF] = r
            except Exception as e:
                RESULTS[fname][oname][OF] = None
                print(f"  ERROR {fname}/{oname}/OF{OF}: {e}")

print("All simulations complete. RESULTS cached in memory.")
print(f"Total data points: {len(FUELS)*len(OXIDIZERS)*len(OF_RATIOS)}")

# ── Also save to JSON (survives kernel restarts if saved) ──────
with open('results_cache.json', 'w') as f:
    json.dump(RESULTS, f, indent=2)
print("Results saved to results_cache.json")

# ── Quick verification ─────────────────────────────────────────
print("\nQuick check — Ethanol/LMP103S/OF=6:")
r = RESULTS['Ethanol']['LMP103S'][6]
print(f"  T_c={r['T_c']}K  Isp={r['Isp']}s  c*={r['c_star']}m/s")
print(f"  Top exhaust: {r['exhaust']}")
print("\n✓ Cell 0 complete. All subsequent cells use RESULTS dict.")

!pip install cantera -q
import cantera as ct
import numpy as np
import matplotlib.pyplot as plt
print(f"Cantera version: {ct.__version__}")
print("Installation successful.")

# We use GRI-Mech 3.0 — standard combustion mechanism
# For LMP-103S (ADN-based), we model the key decomposition
# products: N2, H2O, O2, NO — and combust with hydrocarbon fuels
# GRI-Mech covers all these species accurately

gas = ct.Solution('gri30.yaml')
print(f"Mechanism: GRI 3.0")
print(f"Number of species: {gas.n_species}")
print(f"Number of reactions: {gas.n_reactions}")
print("Mechanism loaded successfully.")

# LMP-103S decomposition product composition
# Molar fractions calculated from mass fractions
# N2: MW=28, H2O: MW=18, O2: MW=32

# Mass fractions from Larsson et al. 2011
mf_N2  = 0.44
mf_H2O = 0.34
mf_O2  = 0.22

# Convert to mole fractions
moles_N2  = mf_N2  / 28
moles_H2O = mf_H2O / 18
moles_O2  = mf_O2  / 32
total_moles = moles_N2 + moles_H2O + moles_O2

xf_N2  = moles_N2  / total_moles
xf_H2O = moles_H2O / total_moles
xf_O2  = moles_O2  / total_moles

print("LMP-103S decomposition product mole fractions:")
print(f"  N2:  {xf_N2:.4f}")
print(f"  H2O: {xf_H2O:.4f}")
print(f"  O2:  {xf_O2:.4f}")
print(f"  Sum: {xf_N2+xf_H2O+xf_O2:.4f} (should be 1.0)")

# Store as dictionary for use in simulations
LMP103S_decomp = {
    'N2' : xf_N2,
    'H2O': xf_H2O,
    'O2' : xf_O2
}

# ══════════════════════════════════════════════════════════════
# CELL 4 — Clean thermochemical analysis
# Focus: effect of ADN decomposition diluents on performance
# ══════════════════════════════════════════════════════════════

def biprop_equilibrium(fuel_formula, fuel_MW, OF_mass,
                        oxidizer_type='LMP103S', P_bar=25):
    """
    Bipropellant equilibrium using Cantera.

    Two oxidizer modes:
    - 'LMP103S': ADN decomp products (N2+H2O+O2) — realistic
    - 'pure_O2':  Pure oxygen — theoretical maximum baseline

    fuel_formula: dict of GRI-Mech species and mole amounts
                  representing the fuel elemental composition
    fuel_MW:      molecular weight of fuel (g/mol)
    OF_mass:      oxidizer/fuel mass ratio
    """
    gas = ct.Solution('gri30.yaml')
    P_pa = P_bar * 1e5

    # ── Oxidizer definitions ────────────────────────────────────
    if oxidizer_type == 'LMP103S':
        # ADN-based LMP-103S decomposition products
        # From Larsson et al. 2011 — validated composition
        ox_species = {'O2': 0.1657, 'N2': 0.3789, 'H2O': 0.4554}
        MW_ox = 0.1657*32 + 0.3789*28 + 0.4554*18  # 24.11 g/mol

    elif oxidizer_type == 'pure_O2':
        # Theoretical pure oxygen — maximum performance baseline
        ox_species = {'O2': 1.0}
        MW_ox = 32.0

    elif oxidizer_type == 'H2O2_90':
        # 90% H2O2 for comparison with PoliMi thesis
        # H2O2 → H2O + 0.5 O2 decomposition
        # 90% H2O2 + 10% H2O by mass
        # Decomp: 0.9 mol H2O2 → 0.9 H2O + 0.45 O2
        #         0.1 mol H2O remains
        # Mole fractions after decomp:
        n_H2O = 0.9 + 0.1/18*18  # simplified
        ox_species = {'O2': 0.45/1.45, 'H2O': 1.0/1.45}
        MW_ox = 0.45/1.45*32 + 1.0/1.45*18  # ≈ 22.3

    else:
        raise ValueError(f"Unknown oxidizer: {oxidizer_type}")

    # ── Mass to mole ratio conversion ──────────────────────────
    # OF_mass = mass_ox / mass_fuel
    # moles_ox / moles_fuel = OF_mass * (MW_fuel / MW_ox)
    mole_ratio = OF_mass * (fuel_MW / MW_ox)

    # ── Build mixture ──────────────────────────────────────────
    mixture = {}
    for sp, xf in ox_species.items():
        mixture[sp] = mixture.get(sp, 0) + xf * mole_ratio
    for sp, moles in fuel_formula.items():
        mixture[sp] = mixture.get(sp, 0) + moles * 1.0

    # ── Equilibrate at constant H, P ──────────────────────────
    gas.TPX = 300.0, P_pa, mixture
    gas.equilibrate('HP')

    T_c   = gas.T
    gamma = gas.cp / gas.cv
    MW_ex = gas.mean_molecular_weight
    R_sp  = 8314.0 / MW_ex

    # ── Isp via characteristic velocity method ─────────────────
    Gam    = np.sqrt(gamma) * (2/(gamma+1))**((gamma+1)/(2*(gamma-1)))
    c_star = np.sqrt(R_sp * T_c) / Gam
    Pe     = 1.0e5   # sea level exit pressure
    Cf     = Gam * np.sqrt(2*gamma/(gamma-1)*(1-(Pe/P_pa)**((gamma-1)/gamma)))
    Isp    = Cf * c_star / 9.80665

    # ── Density impulse (mission-level metric) ─────────────────
    # rho_LMP103S ≈ 1240 kg/m3, rho_ethanol ≈ 789 kg/m3
    # rho_mix = rho_ox*rho_f / (OF*rho_f + rho_ox)
    rho_ox = {'LMP103S':1240, 'pure_O2':1140, 'H2O2_90':1390}
    rho_fu = {'C2H4':567, 'CH4':422, 'C2H4_rp1':820}
    # simplified density impulse
    Isp_d  = Isp  # will refine later

    # ── Key exhaust species ────────────────────────────────────
    top5 = np.argsort(gas.X)[-5:][::-1]
    exhaust = {gas.species_names[i]: round(float(gas.X[i]),4)
               for i in top5}

    return {
        'T_c'    : round(T_c, 1),
        'Isp'    : round(Isp, 2),
        'c_star' : round(c_star, 1),
        'gamma'  : round(gamma, 4),
        'MW_ex'  : round(MW_ex, 3),
        'exhaust': exhaust,
    }


# ── Fuel definitions in GRI-Mech species ──────────────────────
# C2H4 (ethylene) IS in GRI-Mech — verified
# We use it as ethanol proxy and RP-1 proxy
fuels = {
    'Ethanol (C2H5OH)': {
        'formula': {'C2H4': 1.0, 'H2': 1.0},  # C2H6 ≈ ethanol C skeleton
        'MW'     : 46.07,
    },
    'RP-1 (C12H24)': {
        'formula': {'C2H4': 6.0},              # CH2 repeat unit × 6
        'MW'     : 168.32,
    },
    'Methane (CH4)': {
        'formula': {'CH4': 1.0},               # exact
        'MW'     : 16.04,
    },
}

# ── Run full comparison ────────────────────────────────────────
OF_ratios = [2, 4, 6, 8, 10]
P_bar     = 25
oxidizers = ['LMP103S', 'pure_O2']

all_results = {}

for fname, fdata in fuels.items():
    all_results[fname] = {}
    print(f"\n{'═'*70}")
    print(f"FUEL: {fname}")
    print(f"{'═'*70}")

    for ox in oxidizers:
        res = []
        print(f"\n  Oxidizer: {ox:10s} | P={P_bar}bar")
        print(f"  {'O/F':>5} | {'T_c(K)':>8} | {'Isp(s)':>8} | "
              f"{'c*(m/s)':>9} | {'MW_ex':>7} | Top exhaust")
        print(f"  {'-'*65}")

        for OF in OF_ratios:
            try:
                r = biprop_equilibrium(
                    fdata['formula'], fdata['MW'],
                    OF, ox, P_bar
                )
                res.append((OF, r))
                top3 = ', '.join(
                    f"{sp}:{v:.3f}"
                    for sp,v in list(r['exhaust'].items())[:3]
                )
                print(f"  {OF:>5} | {r['T_c']:>8.1f} | "
                      f"{r['Isp']:>8.2f} | {r['c_star']:>9.1f} | "
                      f"{r['MW_ex']:>7.3f} | {top3}")
            except Exception as e:
                print(f"  {OF:>5} | ERROR: {e}")
                res.append((OF, None))

        all_results[fname][ox] = res

print("\n\nDone. Run Cell 5 to plot and quantify diluent penalty.")

# ══════════════════════════════════════════════════════════════
# CELL 5 — Main Comparison Plots (Paper Figure 1 & 2)
# ══════════════════════════════════════════════════════════════

fig = plt.figure(figsize=(16, 10))
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.38, wspace=0.32)

fig.suptitle(
    'Thermochemical Performance: LMP-103S vs Pure O₂ Oxidizer\n'
    'Equilibrium Analysis at P = 25 bar (Sea-Level Expansion)',
    fontsize=13, fontweight='bold', y=1.01
)

fuel_list = list(FUELS.keys())

for col, fname in enumerate(fuel_list):
    fdata = FUELS[fname]

    # Extract data
    data = {}
    for oname in OXIDIZERS:
        data[oname] = {
            'T'  : [RESULTS[fname][oname][OF]['T_c']  for OF in OF_RATIOS],
            'Isp': [RESULTS[fname][oname][OF]['Isp']  for OF in OF_RATIOS],
        }

    # ── Row 0: Temperature ──────────────────────────────────
    ax = fig.add_subplot(gs[0, col])
    for oname, odata in OXIDIZERS.items():
        ax.plot(OF_RATIOS, data[oname]['T'],
                color=odata['color'], ls=odata['ls'],
                marker=fdata['marker'],
                label=f"{'LMP-103S' if oname=='LMP103S' else 'Pure O₂'}")
    ax.set_title(fname, fontweight='bold')
    ax.set_xlabel('O/F Ratio (mass)')
    ax.set_ylabel('Chamber Temperature (K)')
    ax.legend(fontsize=9)
    ax.set_xticks(OF_RATIOS)

    # Annotation: temperature penalty at OF=4
    T_lmp = data['LMP103S']['T'][1]  # OF=4
    T_o2  = data['Pure_O2']['T'][1]
    penalty = (T_o2 - T_lmp) / T_o2 * 100
    ax.annotate(f'ΔT={penalty:.0f}%\n@O/F=4',
                xy=(4, T_lmp), xytext=(5.5, T_lmp*0.75),
                arrowprops=dict(arrowstyle='->', color='gray'),
                fontsize=8, color='gray')

    # ── Row 1: Isp ─────────────────────────────────────────
    ax2 = fig.add_subplot(gs[1, col])
    for oname, odata in OXIDIZERS.items():
        ax2.plot(OF_RATIOS, data[oname]['Isp'],
                 color=odata['color'], ls=odata['ls'],
                 marker=fdata['marker'],
                 label=f"{'LMP-103S' if oname=='LMP103S' else 'Pure O₂'}")
    ax2.set_xlabel('O/F Ratio (mass)')
    ax2.set_ylabel('Specific Impulse, Isp (s)')
    ax2.legend(fontsize=9)
    ax2.set_xticks(OF_RATIOS)

plt.tight_layout()
plt.savefig('fig1_performance_comparison.png',
            dpi=200, bbox_inches='tight')
plt.show()
print("Figure 1 saved.")

# ══════════════════════════════════════════════════════════════
# CELL 6 — Diluent Penalty Quantification (Paper Table 1 + Fig 2)
# This is the CORE FINDING of the paper
# ══════════════════════════════════════════════════════════════

print("="*68)
print("TABLE 1 — LMP-103S DILUENT PENALTY vs PURE O2 BASELINE")
print("Quantifying performance loss from N2 and H2O inert diluents")
print("="*68)

penalty_data = {}

for fname in FUELS:
    penalty_data[fname] = {'OF':[], 'dT_pct':[], 'dIsp_pct':[],
                            'dT_abs':[], 'dIsp_abs':[]}
    print(f"\n{fname}:")
    print(f"  {'O/F':>4} | {'T_LMP(K)':>9} | {'T_O2(K)':>9} | "
          f"{'ΔT(K)':>7} | {'ΔT%':>7} | "
          f"{'Isp_LMP':>8} | {'Isp_O2':>7} | {'ΔIsp%':>8}")
    print(f"  {'-'*75}")

    for OF in OF_RATIOS:
        r_lmp = RESULTS[fname]['LMP103S'][OF]
        r_o2  = RESULTS[fname]['Pure_O2'][OF]
        if not r_lmp or not r_o2:
            continue

        dT_abs  = r_o2['T_c']  - r_lmp['T_c']
        dIsp_abs= r_o2['Isp']  - r_lmp['Isp']
        dT_pct  = dT_abs  / r_o2['T_c']  * 100
        dIsp_pct= dIsp_abs/ r_o2['Isp']  * 100

        penalty_data[fname]['OF'].append(OF)
        penalty_data[fname]['dT_pct'].append(dT_pct)
        penalty_data[fname]['dIsp_pct'].append(dIsp_pct)
        penalty_data[fname]['dT_abs'].append(dT_abs)
        penalty_data[fname]['dIsp_abs'].append(dIsp_abs)

        print(f"  {OF:>4} | {r_lmp['T_c']:>9.1f} | {r_o2['T_c']:>9.1f} | "
              f"{dT_abs:>7.1f} | {dT_pct:>6.1f}% | "
              f"{r_lmp['Isp']:>8.2f} | {r_o2['Isp']:>7.2f} | "
              f"{dIsp_pct:>7.1f}%")

    avg_dT   = np.mean(penalty_data[fname]['dT_pct'])
    avg_dIsp = np.mean(penalty_data[fname]['dIsp_pct'])
    print(f"  {'MEAN':>4} | {'':>9} | {'':>9} | {'':>7} | "
          f"{avg_dT:>6.1f}% | {'':>8} | {'':>7} | {avg_dIsp:>7.1f}%")

# ── Figure 2: Penalty curves ──────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))

fig.suptitle(
    'Performance Penalty of ADN Decomposition Diluents\n'
    '(N₂ + H₂O inerts vs Pure O₂ baseline) | P = 25 bar',
    fontweight='bold'
)

for fname, fdata in FUELS.items():
    pd_f = penalty_data[fname]
    ax1.plot(pd_f['OF'], pd_f['dT_pct'],
             color=fdata['color'], marker=fdata['marker'],
             label=fname)
    ax2.plot(pd_f['OF'], pd_f['dIsp_pct'],
             color=fdata['color'], marker=fdata['marker'],
             label=fname)

ax1.set_xlabel('O/F Ratio (mass)')
ax1.set_ylabel('Temperature Penalty (%)')
ax1.set_title('Combustion Temperature Reduction')
ax1.legend()
ax1.set_xticks(OF_RATIOS)

ax2.set_xlabel('O/F Ratio (mass)')
ax2.set_ylabel('Isp Penalty (%)')
ax2.set_title('Specific Impulse Reduction')
ax2.legend()
ax2.set_xticks(OF_RATIOS)

plt.tight_layout()
plt.savefig('fig2_diluent_penalty.png', dpi=200, bbox_inches='tight')
plt.show()
print("\nFigure 2 saved.")

# ── Key finding summary ───────────────────────────────────────
print("\n" + "="*55)
print("KEY FINDING SUMMARY")
print("="*55)
for fname in FUELS:
    avg_T   = np.mean(penalty_data[fname]['dT_pct'])
    avg_Isp = np.mean(penalty_data[fname]['dIsp_pct'])
    print(f"{fname:10s}: avg T penalty={avg_T:.1f}%  "
          f"avg Isp penalty={avg_Isp:.1f}%")

# ══════════════════════════════════════════════════════════════
# CELL 7 — Pressure Sweep (Paper Figure 3)
# Effect of chamber pressure on diluent penalty
# ══════════════════════════════════════════════════════════════

P_RANGE = [10, 15, 20, 25, 30, 40]  # bar
OF_FIXED = 6  # fixed O/F for pressure sweep

print("Pressure sweep — this may take ~60 seconds...")

pres_results = {}
for fname in FUELS:
    pres_results[fname] = {}
    for oname in OXIDIZERS:
        pres_results[fname][oname] = {'P':[], 'T':[], 'Isp':[], 'cstar':[]}
        for P in P_RANGE:
            try:
                r = run_equilibrium(fname, oname, OF_FIXED, P)
                pres_results[fname][oname]['P'].append(P)
                pres_results[fname][oname]['T'].append(r['T_c'])
                pres_results[fname][oname]['Isp'].append(r['Isp'])
                pres_results[fname][oname]['cstar'].append(r['c_star'])
            except Exception as e:
                print(f"  P={P} {fname}/{oname}: {e}")

print("Pressure sweep complete.")

# ── Plot ──────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle(
    f'Effect of Chamber Pressure on Performance\n'
    f'O/F = {OF_FIXED} (mass) | LMP-103S vs Pure O₂',
    fontweight='bold'
)

metrics = [('T','Chamber Temperature (K)'),
           ('Isp','Specific Impulse (s)'),
           ('cstar','Characteristic Velocity c* (m/s)')]

for ax, (metric, ylabel) in zip(axes, metrics):
    for fname, fdata in FUELS.items():
        for oname, odata in OXIDIZERS.items():
            pr = pres_results[fname][oname]
            label = f"{fname}/{'LMP-103S' if oname=='LMP103S' else 'O₂'}"
            ax.plot(pr['P'], pr[metric],
                    color=fdata['color'], ls=odata['ls'],
                    marker=fdata['marker'], label=label, alpha=0.85)
    ax.set_xlabel('Chamber Pressure (bar)')
    ax.set_ylabel(ylabel)
    ax.set_xticks(P_RANGE)

# Only show legend on first plot to avoid clutter
axes[0].legend(fontsize=7, ncol=2)

plt.tight_layout()
plt.savefig('fig3_pressure_sweep.png', dpi=200, bbox_inches='tight')
plt.show()

# Print key numbers
print(f"\nPressure effect on Isp (Ethanol/LMP103S, O/F={OF_FIXED}):")
pr = pres_results['Ethanol']['LMP103S']
for i, P in enumerate(pr['P']):
    print(f"  P={P:3d} bar: Isp={pr['Isp'][i]:.2f} s  "
          f"c*={pr['cstar'][i]:.1f} m/s")

# ══════════════════════════════════════════════════════════════
# CELL 8 — Monte Carlo Uncertainty Analysis (Paper Figure 4)
# This is what elevates this work above a CEA survey
# Quantifies how uncertainty in LMP-103S composition
# propagates to performance predictions
# ══════════════════════════════════════════════════════════════

np.random.seed(42)
N_SAMPLES = 500   # Monte Carlo samples (500 is fast, 2000 for paper)

# ── Uncertainty sources ───────────────────────────────────────
# Based on Larsson et al. 2011 reported uncertainties
# LMP-103S decomposition products have ±5% composition uncertainty
# Chamber pressure uncertainty ±2 bar (sensor accuracy)
# O/F ratio uncertainty ±0.3 (injector tolerance)

UNCERTAINTIES = {
    'xO2_std' : 0.1657 * 0.05,   # ±5% of nominal
    'xN2_std' : 0.3789 * 0.05,
    'xH2O_std': 0.4554 * 0.05,
    'P_std'   : 1.0,              # ±1 bar (1 sigma)
    'OF_std'  : 0.2,              # ±0.2 O/F ratio
}

print(f"Running Monte Carlo: {N_SAMPLES} samples per condition...")
print("This evaluates uncertainty in LMP-103S composition,")
print("chamber pressure, and O/F ratio simultaneously.\n")

# Focus: Ethanol/LMP103S at OF=6, P=25 bar (nominal optimum)
fname_mc = 'Ethanol'
OF_nom   = 6
P_nom    = 25

T_samples   = []
Isp_samples = []
cstar_samples = []

for i in range(N_SAMPLES):
    # Sample uncertain inputs (Latin Hypercube approximated via normal)
    xO2  = max(0.05, np.random.normal(0.1657, UNCERTAINTIES['xO2_std']))
    xN2  = max(0.05, np.random.normal(0.3789, UNCERTAINTIES['xN2_std']))
    xH2O = max(0.05, np.random.normal(0.4554, UNCERTAINTIES['xH2O_std']))
    # Renormalize
    total = xO2 + xN2 + xH2O
    xO2 /= total; xN2 /= total; xH2O /= total

    P_sample  = max(5, np.random.normal(P_nom, UNCERTAINTIES['P_std']))
    OF_sample = max(1, np.random.normal(OF_nom, UNCERTAINTIES['OF_std']))

    ox_sample = {'O2': xO2, 'N2': xN2, 'H2O': xH2O}
    MW_ox_s   = xO2*32 + xN2*28 + xH2O*18

    try:
        gas = ct.Solution('gri30.yaml')
        fdata = FUELS[fname_mc]
        mole_ratio = OF_sample * (fdata['MW'] / MW_ox_s)
        mixture = {}
        for sp, xf in ox_sample.items():
            mixture[sp] = mixture.get(sp,0) + xf * mole_ratio
        for sp, m in fdata['formula'].items():
            mixture[sp] = mixture.get(sp,0) + m

        gas.TPX = 300.0, P_sample*1e5, mixture
        gas.equilibrate('HP')

        T   = gas.T
        gam = gas.cp / gas.cv
        MW  = gas.mean_molecular_weight
        R   = 8314.0 / MW
        Gvdk= np.sqrt(gam)*(2/(gam+1))**((gam+1)/(2*(gam-1)))
        cs  = np.sqrt(R*T)/Gvdk
        Cf  = Gvdk*np.sqrt(2*gam/(gam-1)*(1-(1e5/(P_sample*1e5))**((gam-1)/gam)))
        Isp = Cf*cs/G0

        T_samples.append(T)
        Isp_samples.append(Isp)
        cstar_samples.append(cs)
    except:
        pass

T_arr   = np.array(T_samples)
Isp_arr = np.array(Isp_samples)
cs_arr  = np.array(cstar_samples)

print(f"Successful samples: {len(T_arr)}/{N_SAMPLES}")
print(f"\nUNCERTAINTY RESULTS — Ethanol/LMP-103S, O/F={OF_nom}, P={P_nom}bar:")
print(f"{'Metric':<20} {'Mean':>9} {'Std':>9} "
      f"{'95% CI Low':>12} {'95% CI High':>12} {'CV%':>7}")
print("-"*72)

for name, arr in [('T_c (K)', T_arr),
                   ('Isp (s)', Isp_arr),
                   ('c* (m/s)', cs_arr)]:
    mean  = np.mean(arr)
    std   = np.std(arr)
    ci_lo = np.percentile(arr, 2.5)
    ci_hi = np.percentile(arr, 97.5)
    cv    = std/mean*100
    print(f"{name:<20} {mean:>9.2f} {std:>9.3f} "
          f"{ci_lo:>12.2f} {ci_hi:>12.2f} {cv:>6.2f}%")

# ── Figure 4: Uncertainty distributions ──────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle(
    f'Monte Carlo Uncertainty Analysis — Ethanol/LMP-103S\n'
    f'O/F={OF_nom}, P={P_nom} bar | N={len(T_arr)} samples\n'
    f'Input uncertainties: composition ±5%, pressure ±1bar, O/F ±0.2',
    fontweight='bold'
)

for ax, (arr, name, unit, color) in zip(axes, [
    (T_arr,   'Chamber Temperature', 'K',     '#2563A8'),
    (Isp_arr, 'Specific Impulse',    's',     '#DC2626'),
    (cs_arr,  'Char. Velocity c*',   'm/s',   '#059669'),
]):
    ax.hist(arr, bins=40, color=color, alpha=0.7, edgecolor='white')
    mean = np.mean(arr); std = np.std(arr)
    ax.axvline(mean, color='black', ls='-',  lw=2, label=f'Mean={mean:.1f}')
    ax.axvline(mean-2*std, color='red', ls='--', lw=1.5,
               label=f'±2σ: [{mean-2*std:.1f}, {mean+2*std:.1f}]')
    ax.axvline(mean+2*std, color='red', ls='--', lw=1.5)
    ax.set_xlabel(f'{name} ({unit})')
    ax.set_ylabel('Frequency')
    ax.set_title(f'{name}\nCV = {std/mean*100:.2f}%')
    ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig('fig4_uncertainty.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure 4 saved.")

# ══════════════════════════════════════════════════════════════
# CELL 9 — Mission Trade Study (Paper Figure 5)
# Rocket equation: what do these Isp differences mean
# for an actual deep-space mission?
# ══════════════════════════════════════════════════════════════

# ── Mission scenarios ─────────────────────────────────────────
MISSIONS = {
    'LEO Circularisation'    : {'dv': 150,  'desc': 'Orbit raising'},
    'GTO to GEO'             : {'dv': 1500, 'desc': 'Apogee kick'},
    'Lunar Orbit Insertion'  : {'dv': 900,  'desc': 'LOI burn'},
    'Mars Orbit Insertion'   : {'dv': 900,  'desc': 'MOI burn'},
    'Deep Space Correction'  : {'dv': 300,  'desc': 'TCM manoeuvre'},
}

# Initial wet mass (kg) — typical small spacecraft
M_wet = 500  # kg

print("="*68)
print("MISSION TRADE STUDY — Propellant Mass Comparison")
print(f"Spacecraft wet mass: {M_wet} kg")
print("="*68)

# Use optimal O/F for each propellant (peak Isp)
optimal_OF = {}
for fname in FUELS:
    best_OF  = max(OF_RATIOS,
                   key=lambda OF: RESULTS[fname]['LMP103S'][OF]['Isp'])
    optimal_OF[fname] = best_OF

print(f"\nOptimal O/F ratios (peak Isp with LMP-103S):")
for fname in FUELS:
    OF_opt = optimal_OF[fname]
    isp    = RESULTS[fname]['LMP103S'][OF_opt]['Isp']
    print(f"  {fname:10s}: O/F={OF_opt}  Isp={isp:.2f}s")

# ── Tsiolkovsky rocket equation ───────────────────────────────
# m_prop = m_wet * (1 - exp(-dv / (Isp * g0)))
def propellant_mass(Isp, dv, m_wet):
    return m_wet * (1 - np.exp(-dv / (Isp * G0)))

# ── Compute for all missions and fuels ────────────────────────
print("\n\nPROPELLANT MASS SAVINGS: LMP-103S vs Pure O2 Oxidizer")
print("(negative = LMP-103S requires MORE propellant)")

trade_results = {}

for mname, mdata in MISSIONS.items():
    dv = mdata['dv']
    trade_results[mname] = {}
    print(f"\n{mname} (Δv = {dv} m/s):")
    print(f"  {'Fuel':10s} | {'Isp_LMP':>8} | {'m_prop_LMP':>11} | "
          f"{'Isp_O2':>7} | {'m_prop_O2':>10} | {'Δm_prop':>10} | {'Δm%':>7}")
    print(f"  {'-'*73}")

    for fname in FUELS:
        OF_opt   = optimal_OF[fname]
        isp_lmp  = RESULTS[fname]['LMP103S'][OF_opt]['Isp']
        isp_o2   = RESULTS[fname]['Pure_O2'][OF_opt]['Isp']
        mp_lmp   = propellant_mass(isp_lmp, dv, M_wet)
        mp_o2    = propellant_mass(isp_o2,  dv, M_wet)
        dm       = mp_lmp - mp_o2
        dm_pct   = dm / mp_o2 * 100

        trade_results[mname][fname] = {
            'mp_lmp':mp_lmp, 'mp_o2':mp_o2, 'dm':dm, 'dm_pct':dm_pct
        }

        print(f"  {fname:10s} | {isp_lmp:>8.2f} | {mp_lmp:>10.2f}kg | "
              f"{isp_o2:>7.2f} | {mp_o2:>9.2f}kg | "
              f"{dm:>+9.2f}kg | {dm_pct:>+6.1f}%")

# ── Figure 5: Mission trade ───────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle(
    f'Mission-Level Impact of LMP-103S Diluent Penalty\n'
    f'Spacecraft wet mass = {M_wet} kg | Optimal O/F per fuel',
    fontweight='bold'
)

mission_names_short = [m.replace(' ', '\n') for m in MISSIONS.keys()]
dv_vals = [MISSIONS[m]['dv'] for m in MISSIONS]

# Plot 1: Propellant mass for each mission (Ethanol, both oxidizers)
ax = axes[0]
x = np.arange(len(MISSIONS))
w = 0.35
lmp_masses = [trade_results[m]['Ethanol']['mp_lmp'] for m in MISSIONS]
o2_masses  = [trade_results[m]['Ethanol']['mp_o2']  for m in MISSIONS]

bars1 = ax.bar(x-w/2, lmp_masses, w, label='LMP-103S',
               color='#DC2626', alpha=0.8)
bars2 = ax.bar(x+w/2, o2_masses,  w, label='Pure O₂',
               color='#7C3AED', alpha=0.8)
ax.set_xticks(x)
ax.set_xticklabels(mission_names_short, fontsize=8)
ax.set_ylabel('Propellant Mass Required (kg)')
ax.set_title('Ethanol Fuel — Propellant Mass per Mission')
ax.legend()

# Plot 2: Extra propellant mass penalty (kg) across all fuels and missions
ax2 = axes[1]
dv_cont = np.linspace(100, 2000, 200)
for fname, fdata in FUELS.items():
    OF_opt  = optimal_OF[fname]
    isp_lmp = RESULTS[fname]['LMP103S'][OF_opt]['Isp']
    isp_o2  = RESULTS[fname]['Pure_O2'][OF_opt]['Isp']
    dm_cont = [propellant_mass(isp_lmp, dv, M_wet) -
               propellant_mass(isp_o2,  dv, M_wet)
               for dv in dv_cont]
    ax2.plot(dv_cont, dm_cont, color=fdata['color'],
             ls='-', label=fname)

ax2.axhline(0, color='black', ls='--', lw=1)
ax2.set_xlabel('Mission Δv (m/s)')
ax2.set_ylabel('Extra Propellant Mass (kg)\n[LMP-103S vs Pure O₂]')
ax2.set_title('Propellant Penalty vs Mission Δv\n(all fuels)')
ax2.legend()

# Mark key missions
for mname, mdata in MISSIONS.items():
    ax2.axvline(mdata['dv'], color='gray', ls=':', lw=0.8, alpha=0.6)
    ax2.text(mdata['dv']+15, ax2.get_ylim()[1]*0.92,
             mname.split()[0], fontsize=7, color='gray', rotation=90)

plt.tight_layout()
plt.savefig('fig5_mission_trade.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure 5 saved.")